version: '1.0'

services:

  postgres:
    image: postgres:11.13
    container_name: postgres_test_t1_gladun
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=testsDB